import {validateConfig,parseChannelUrl} from '../assets/js/model.js';
const $=id=>document.getElementById(id);let subjects=[],channels=[],editing=null,editingSubject=null,ready=false,publishedSubjects=[];
function node(tag,text){const n=document.createElement(tag);if(text)n.textContent=text;return n}
function action(text,fn){const b=node('button',text);b.type='button';b.onclick=fn;return b}
function message(text){$('message').textContent=text;$('message').className='notice'}
function move(items,index,delta){const to=index+delta;if(to<0||to>=items.length)return;[items[index],items[to]]=[items[to],items[index]];items.forEach((c,i)=>c.order=i);render()}
function reset(){editing=null;$('channel-form').reset();$('save-channel').textContent='Add to draft / إضافة لمسودة';$('cancel-edit').hidden=true}
function resetSubject(){editingSubject=null;$('subject-form').reset();$('subject-id').disabled=false;$('save-subject').textContent='Add subject';$('cancel-subject').hidden=true}
function render(){const selected=$('subject').value;$('subject').replaceChildren();subjects.forEach(s=>{const o=node('option',s.name.en+' / '+s.name.ar);o.value=s.id;$('subject').append(o)});$('subject').value=subjects.some(s=>s.id===selected)?selected:subjects[0]?.id||'';
$('channel-list').replaceChildren();channels.forEach((c,i)=>{const row=node('div');row.className='admin-row';const copy=node('div');copy.className='row-text';copy.append(node('strong',c.teacher),node('small',`${c.url} · ${c.subject} · ${c.grade||'All grades'} · ${c.enabled?'Enabled':'Disabled'}`));row.append(copy,action('Edit',()=>{editing=c.id;for(const key of ['url','subject','teacher','grade','enabled'])$(key).value=String(c[key]??'');$('save-channel').textContent='Save changes';$('cancel-edit').hidden=false;$('url').focus();$('channel-form').scrollIntoView({block:'center'})}),action(c.enabled?'Disable':'Enable',()=>{c.enabled=!c.enabled;render();message('Draft updated. Export and commit to publish.')}),action('↑',()=>move(channels,i,-1)),action('↓',()=>move(channels,i,1)),action('Delete',()=>{if(confirm(`Remove ${c.teacher} from this draft?`)){channels.splice(i,1);if(editing===c.id)reset();render()}}));$('channel-list').append(row)});
$('subject-list').replaceChildren();subjects.forEach((s,i)=>{const row=node('div');row.className='admin-row';const copy=node('div');copy.className='row-text';copy.append(node('strong',`${s.icon||'▤'} ${s.name.en} / ${s.name.ar}`),node('small',s.id));row.append(copy,action('Edit',()=>{editingSubject=s.id;$('subject-id').value=s.id;$('subject-id').disabled=true;$('subject-icon').value=s.icon||'';$('subject-en').value=s.name.en;$('subject-ar').value=s.name.ar;$('save-subject').textContent='Save subject';$('cancel-subject').hidden=false;$('subject-en').focus()}),action('↑',()=>move(subjects,i,-1)),action('↓',()=>move(subjects,i,1)),action('Delete',()=>{if(channels.some(c=>c.subject===s.id))return message('Reassign or delete this subject’s channels first.');if(confirm(`Remove ${s.name.en}?`)){subjects.splice(i,1);if(editingSubject===s.id)resetSubject();render()}}));$('subject-list').append(row)})}
$('cancel-edit').onclick=reset;$('cancel-subject').onclick=resetSubject;
$('channel-form').onsubmit=e=>{e.preventDefault();if(!ready)return;try{const url=parseChannelUrl($('url').value.trim()).url;const existing=channels.find(c=>c.id===editing);const c={id:editing||crypto.randomUUID(),url,subject:$('subject').value,teacher:$('teacher').value.trim(),grade:$('grade').value.trim(),enabled:$('enabled').value==='true',order:existing?.order??channels.length,dateAdded:existing?.dateAdded??new Date().toISOString()};const next=editing?channels.map(x=>x.id===editing?c:x):[...channels,c];validateConfig(subjects,next);channels=next;reset();render();message('Channel saved to draft only — not published. / القناة محفوظة كمسودة فقط ولم تُنشر. استخدم نموذج إضافة قناة من هنا للنشر المباشر، أو صدّر الملفات وارفعها للمستودع.')}catch(e){message(e.message)}};
$('subject-form').onsubmit=e=>{e.preventDefault();if(!ready)return;try{const s={id:$('subject-id').value.trim(),name:{en:$('subject-en').value.trim(),ar:$('subject-ar').value.trim()},icon:$('subject-icon').value.trim()||'▤',order:subjects.find(s=>s.id===editingSubject)?.order??subjects.length};const next=editingSubject?subjects.map(x=>x.id===editingSubject?s:x):[...subjects,s];validateConfig(next,channels);subjects=next;resetSubject();render();message('Subject saved to draft.')}catch(e){message(e.message)}};
function download(filename,data){const a=node('a');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}));a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('export').onclick=()=>{if(!ready)return;try{validateConfig(subjects,channels);download('subjects.json',subjects);download('approved-channels.json',channels);message('Configuration exported. Your browser may ask permission for multiple downloads. Commit both files into data/ to publish.')}catch(e){message(e.message)}};
for(const [id,type]of [['import-subjects','subjects'],['import-channels','channels']])$(id).onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw new Error('Configuration file is too large.');const data=JSON.parse(await file.text());validateConfig(type==='subjects'?data:subjects,type==='channels'?data:channels);if(type==='subjects')subjects=data;else channels=data;reset();resetSubject();render();message('Imported into draft. Export and commit to publish.')}catch(e){message(e.message)}finally{e.target.value=''}};
async function load(){try{const fetchJson=async file=>{const r=await fetch('../data/'+file+'.json',{cache:'no-cache'});if(!r.ok)throw new Error('Could not load configuration.');return r.json()};[subjects,channels]=await Promise.all([fetchJson('subjects'),fetchJson('approved-channels')]);validateConfig(subjects,channels);channels.sort((a,b)=>a.order-b.order);ready=true;publishedSubjects=subjects.map(s=>({...s}));publishedSubjects.forEach(s=>{const o=node('option',s.name.ar+' / '+s.name.en);o.value=s.id;$('publish-subject').append(o)});$('publish-channel').disabled=false;render();try{const status=await fetchJson('sync-status');showSyncStatus(status)}catch{$('sync-status').textContent='Sync status unavailable.'}}catch(e){message(e.message);$('sync-status').textContent='Configuration unavailable. Fix the JSON in GitHub and reload.'}}
load();

if(location.hostname.endsWith('.github.io')){const owner=location.hostname.slice(0,-'.github.io'.length);const root=new URL('../',location.href);const repo=root.pathname.split('/').filter(Boolean)[0]||owner+'.github.io';$('github-add-channel').href=`https://github.com/${owner}/${repo}/actions/workflows/add-channel.yml`;}

let publishing=false;
$('publish-form').onsubmit=async e=>{
 e.preventDefault();if(!ready||publishing)return;
 const status=$('publish-status');
 try{
  const url=parseChannelUrl($('publish-url').value.trim()).url;
  if(!publishedSubjects.some(s=>s.id===$('publish-subject').value))throw new Error('المادة غير منشورة بعد.');
  const workflow=new URL($('github-add-channel').href);
  const [owner,repo]=workflow.pathname.split('/').filter(Boolean);
  if(!/^[\w-]+$/.test(owner)||! /^[\w.-]+$/.test(repo))throw new Error('Invalid repository');
  publishing=true;$('publish-channel').disabled=true;status.textContent='جاري إرسال طلب النشر…';
  const response=await fetch(`https://api.github.com/repos/${owner}/${repo}/actions/workflows/add-channel.yml/dispatches`,{method:'POST',headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${$('publish-token').value.trim()}`,'X-GitHub-Api-Version':'2022-11-28'},body:JSON.stringify({ref:'main',inputs:{channel_url:url,subject:$('publish-subject').value,teacher:$('publish-teacher').value.trim(),grade:$('publish-grade').value.trim()}}),signal:AbortSignal.timeout(20000)});
  if(!response.ok){const errors={401:'مفتاح الإدارة غير صالح أو انتهت صلاحيته.',403:'المفتاح يحتاج صلاحية Actions: Read and write لهذا المستودع.',404:'تحقق من صلاحية المفتاح وأن تحديث إضافة القنوات منشور في المستودع.',422:'تعذر بدء النشر. تحقق من وجود workflow الإضافة على فرع main.'};throw new Error(errors[response.status]||'تعذر إرسال طلب النشر. حاول مرة أخرى.');}
  status.textContent='تم إرسال طلب النشر، وليس تأكيد اكتماله. انتظر المزامنة ثم حدّث الموقع. إذا لم تظهر القناة، راجع سجل التنفيذ من الرابط أدناه.';
  const a=node('a',' متابعة نتيجة النشر');a.href=$('github-add-channel').href;a.target='_blank';a.rel='noopener';status.append(a);
 }catch(error){status.textContent=error.name==='TimeoutError'?'انتهت مهلة الاتصال؛ قد يكون الطلب وصل. تحقق من نتيجة النشر قبل إعادة المحاولة.':error instanceof TypeError?'تعذر الاتصال بـ GitHub. تحقق من الإنترنت.':error.message;}
 finally{publishing=false;$('publish-channel').disabled=false;}
};

function showSyncStatus(status){
 const labels={ok:'تمت المزامنة',partial:'مزامنة جزئية',error:'فشلت المزامنة'};
 const last=status.lastSuccessAt?new Intl.DateTimeFormat('ar-EG',{dateStyle:'medium',timeStyle:'short',timeZone:'Africa/Cairo'}).format(new Date(status.lastSuccessAt)):'لا توجد مزامنة ناجحة';
 $('sync-status').textContent=`الحالة: ${labels[status.status]||status.status}\nآخر نجاح بتوقيت القاهرة: ${last}`;
 for(const channel of status.channels||[])$('sync-status').append(node('p',`${channel.id}: ${labels[channel.status]||channel.status} · ${channel.videoCount??0} درس${channel.error?' · '+channel.error:''}`));
}
$('refresh-status').onclick=async()=>{try{const response=await fetch('../data/sync-status.json',{cache:'no-store'});if(!response.ok)throw new Error();showSyncStatus(await response.json())}catch{$('sync-status').textContent='تعذر تحديث الحالة. حاول مرة أخرى.'}};
