import {validateConfig,parseChannelUrl} from '../assets/js/model.js';
const $=id=>document.getElementById(id);let subjects=[],channels=[],editing=null,editingSubject=null,ready=false;
function node(tag,text){const n=document.createElement(tag);if(text)n.textContent=text;return n}
function action(text,fn){const b=node('button',text);b.type='button';b.onclick=fn;return b}
function message(text){$('message').textContent=text;$('message').className='notice'}
function move(items,index,delta){const to=index+delta;if(to<0||to>=items.length)return;[items[index],items[to]]=[items[to],items[index]];items.forEach((c,i)=>c.order=i);render()}
function reset(){editing=null;$('channel-form').reset();$('save-channel').textContent='Add to draft / إضافة لمسودة';$('cancel-edit').hidden=true}
function resetSubject(){editingSubject=null;$('subject-form').reset();$('subject-id').disabled=false;$('save-subject').textContent='Add subject';$('cancel-subject').hidden=true}
function render(){const selected=$('subject').value;$('subject').replaceChildren();subjects.forEach(s=>{const o=node('option',s.name.en+' / '+s.name.ar);o.value=s.id;$('subject').append(o)});$('subject').value=subjects.some(s=>s.id===selected)?selected:subjects[0]?.id||'';
$('channel-list').replaceChildren();channels.forEach((c,i)=>{const row=node('div');row.className='admin-row';const copy=node('div');copy.className='row-text';copy.append(node('strong',c.teacher),node('small',`${c.url} · ${c.subject} · ${c.grade||'All grades'} · ${c.enabled?'Enabled':'Disabled'}`));row.append(copy,action('Edit',()=>{editing=c.id;for(const key of ['url','subject','teacher','grade','enabled'])$(key).value=String(c[key]??'');$('save-channel').textContent='Save changes';$('cancel-edit').hidden=false;$('url').focus();$('channel-form').scrollIntoView({block:'center'})}),action(c.enabled?'Disable':'Enable',()=>{c.enabled=!c.enabled;render();message('Draft updated. Export and commit to publish.')}),action('↑',()=>move(channels,i,-1)),action('↓',()=>move(channels,i,1)),action('Delete',()=>{if(confirm(`Remove ${c.teacher} from this draft?`)){channels.splice(i,1);if(editing===c.id)reset();render()}}));$('channel-list').append(row)});
$('subject-list').replaceChildren();subjects.forEach((s,i)=>{const row=node('div');row.className='admin-row';const copy=node('div');copy.className='row-text';copy.append(node('strong',`${s.icon||'▤'} ${s.name.en} / ${s.name.ar}`),node('small',s.id));row.append(copy,action('Edit',()=>{editingSubject=s.id;$('subject-id').value=s.id;$('subject-id').disabled=true;$('subject-icon').value=s.icon||'';$('subject-en').value=s.name.en;$('subject-ar').value=s.name.ar;$('save-subject').textContent='Save subject';$('cancel-subject').hidden=false;$('subject-en').focus()}),action('↑',()=>move(subjects,i,-1)),action('↓',()=>move(subjects,i,1)),action('Delete',()=>{if(channels.some(c=>c.subject===s.id))return message('Reassign or delete this subject’s channels first.');if(confirm(`Remove ${s.name.en}?`)){subjects.splice(i,1);if(editingSubject===s.id)resetSubject();render()}}));$('subject-list').append(row)})}
$('cancel-edit').onclick=reset;$('cancel-subject').onclick=resetSubject;
$('channel-form').onsubmit=e=>{e.preventDefault();if(!ready)return;try{const url=parseChannelUrl($('url').value.trim()).url;const existing=channels.find(c=>c.id===editing);const c={id:editing||crypto.randomUUID(),url,subject:$('subject').value,teacher:$('teacher').value.trim(),grade:$('grade').value.trim(),enabled:$('enabled').value==='true',order:existing?.order??channels.length,dateAdded:existing?.dateAdded??new Date().toISOString()};const next=editing?channels.map(x=>x.id===editing?c:x):[...channels,c];validateConfig(subjects,next);channels=next;reset();render();message('Channel saved to draft only — not published. / القناة محفوظة كمسودة فقط ولم تُنشر. استخدم إضافة قناة عبر GitHub للنشر المباشر، أو صدّر الملفات وارفعها للمستودع.')}catch(e){message(e.message)}};
$('subject-form').onsubmit=e=>{e.preventDefault();if(!ready)return;try{const s={id:$('subject-id').value.trim(),name:{en:$('subject-en').value.trim(),ar:$('subject-ar').value.trim()},icon:$('subject-icon').value.trim()||'▤',order:subjects.find(s=>s.id===editingSubject)?.order??subjects.length};const next=editingSubject?subjects.map(x=>x.id===editingSubject?s:x):[...subjects,s];validateConfig(next,channels);subjects=next;resetSubject();render();message('Subject saved to draft.')}catch(e){message(e.message)}};
function download(filename,data){const a=node('a');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}));a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('export').onclick=()=>{if(!ready)return;try{validateConfig(subjects,channels);download('subjects.json',subjects);download('approved-channels.json',channels);message('Configuration exported. Your browser may ask permission for multiple downloads. Commit both files into data/ to publish.')}catch(e){message(e.message)}};
for(const [id,type]of [['import-subjects','subjects'],['import-channels','channels']])$(id).onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw new Error('Configuration file is too large.');const data=JSON.parse(await file.text());validateConfig(type==='subjects'?data:subjects,type==='channels'?data:channels);if(type==='subjects')subjects=data;else channels=data;reset();resetSubject();render();message('Imported into draft. Export and commit to publish.')}catch(e){message(e.message)}finally{e.target.value=''}};
async function load(){try{const fetchJson=async file=>{const r=await fetch('../data/'+file+'.json',{cache:'no-cache'});if(!r.ok)throw new Error('Could not load configuration.');return r.json()};[subjects,channels]=await Promise.all([fetchJson('subjects'),fetchJson('approved-channels')]);validateConfig(subjects,channels);channels.sort((a,b)=>a.order-b.order);ready=true;render();try{const status=await fetchJson('sync-status');$('sync-status').textContent=JSON.stringify(status,null,2)}catch{$('sync-status').textContent='Sync status unavailable.'}}catch(e){message(e.message);$('sync-status').textContent='Configuration unavailable. Fix the JSON in GitHub and reload.'}}
load();

if(location.hostname.endsWith('.github.io')){const owner=location.hostname.slice(0,-'.github.io'.length);const root=new URL('../',location.href);const repo=root.pathname.split('/').filter(Boolean)[0]||owner+'.github.io';$('github-add-channel').href=`https://github.com/${owner}/${repo}/actions/workflows/add-channel.yml`;}
